apiVersion: apps/v1
kind: Deployment
metadata: 
  name: welcomeappdeployment
spec:
  replicas: 2
  strategy:
  type: Recreate
  selector:
    matchLabels:
      app: welcomeapp
  template:
    metadata:
      name: welcomeapppod
      labels:
        app: welcomeapp
        spec: 
          containers:
          - name: welcomeappcontainer
            image: ganesh2152/myapp:v1
            ports:
            - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata: 
  name: welcomeappsvc
spec:
  type: NodePort
  selector:
    app: welcomeapp
    ports:
    - ports: 80
      targetPort: 8501