---
apiVersion: v1
kind: Pod
metadata:
  name: welcomeapppod
  labels:
    app: welcomeapp
spec:
  containers:
  - image: ganesh2152/myimage
    name: welcomeappcontainer
    ports:
    - containerPort: 8501
...
---
apiVersion: v1
kind: Service
metadata:
  name: welcomeappsvc
spec:
  type: ClusterIP
  selector:
    app: welcomeapp
  ports:
  - port: 80
    targetPort: 8501